[package]
name = "hrw"
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/sweet-security/hrw"
description = "A simple, generic implementation of Highest Random Weight (HRW or Rendezvous) hashing"

[dependencies]

[dev-dependencies]
ahash = "0.8"
